package com.github.burningrain.lizard.editor.ui.actions;

public interface Actions {

    String OPEN_PROCESS = "OPEN_PROCESS_ACTION";
    String SAVE_PROCESS = "SAVE_PROCESS";
    String EXPORT_PROCESS = "EXPORT_PROCESS";
    String IMPORT_PROCESS = "IMPORT_PROCESS";

    String LOAD_PLUGIN_DATA_TO_STORE = "LOAD_PLUGIN_DATA_TO_STORE";

    String ADD_VERTEX_TO_EDITOR_ACTION = "ADD_VERTEX_TO_EDITOR_ACTION";
    String ADD_EDGE_TO_EDITOR_ACTION = "ADD_EDGE_TO_EDITOR_ACTION";
    String DRAG_OVER_VERTEX_TO_EDITOR_ACTION = "DRAG_OVER_VERTEX_TO_EDITOR_ACTION";

    String DELETE_SELECTED_VERTEX_ACTION = "DELETE_SELECTED_VERTEX_ACTION";

    String SHOW_ABOUT_LIZARD_EDITOR = "SHOW_ABOUT_LIZARD_EDITOR";

    String SHOW_GRID_SETTINGS = "SHOW_GRID_SETTINGS";

}
